[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
vm-squads = "3XR9BbkbddGNFCbEG59XXEy9MydHZmGZb6jEq4VxQWY7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
